### ISSUE TITLE
z-index issues

### ISSUE THREAD

**Issue by CptTwinkie** [cswendrowski/FoundryVTT-TinyMCE-CustomFilePicker#1]
Foundry recently had a change to the way z-index works when focus changes between windows. This is causing z-index problems with the image and file picker windows.

Correct behavior:
1. Open a journal
2. Click the edit button
3. Click the image button in tinyMCE
3. The image dialog opens above the window

To reproduce the issue:
1. Open a journal [0]
2. Open a second journal [1] (new top)
3. Focus the first journal [0]
4. Click the edit button
5. Click the image button in tinyMCE
6. The image dialog opens below the window

![image](https://user-images.githubusercontent.com/2079751/107601422-faf74c00-6c26-11eb-8523-ea583b3d8b3f.png)

**Comment by cswendrowski** [comment]
I'll look into this, thanks for the report with clear reproduction steps!

**Comment by fel-pt** [comment]
I have something to add to this issue:

If the user has the OneJournal module installed, it will happen to every journal window. I assume the solving the issue as mentioned by @CptTwinkie will also solve this particular case, but I figured I should let you know.

**Comment by cswendrowski** [comment]
This should be resolved as of v1.0.1

**Comment by fel-pt** [comment]
@cswendrowski Just to let you know that this fix also solved the issue with the Paragraph drop down menu I mentioned here: https://github.com/cswendrowski/FoundryVTT-TinyMCE-CustomFilePicker/issues/3

**Comment by cswendrowski** [comment]
That's incredibly lucky, thanks for letting me know @nulmas
