### ISSUE TITLE
Custom File Picker Seems to Block MCE Formatting

### ISSUE THREAD

**Issue by cgplayer2000** [cswendrowski/FoundryVTT-TinyMCE-CustomFilePicker#2]
If TinyMCE Custom File Picker is enabled and after selecting the FilePicker button, I cannot access the Formatting Styles button.  If I don't pick the File Picker, I can still edit formats to my heart's content.  After, I cannot.  The work around is to close what I'm working on, and re-open the journal.  So long as I don't use the file picker on the image select button, everything works.  

I see no relevant error messages in console.  I see a reference to FilePicker, but nothing else.

**Comment by cswendrowski** [comment]
This unfortunately seems to be a TinyMCE bug - My code simply assigns the config options to enable a new button and trigger Foundry's filepicker on it
