### ISSUE TITLE
File Picker opens behind dialog menu

### ISSUE THREAD

**Issue by LorduFreeman** [cswendrowski/FoundryVTT-TinyMCE-CustomFilePicker#5]
![image](https://user-images.githubusercontent.com/72170114/115742461-f66eb280-a390-11eb-8899-cd834e2728ed.png)

Happens without any other modules enabled. Menu is unusable.
Foundry 0.7.9
DnD5 1.2.4
File Picker 1.0.1

**Comment by mech-tools** [comment]
Same here.
Same configuration.

**Comment by CapivaraTupiniquim** [comment]
Com o mesmo problema aqui

**Comment by LorduFreeman** [comment]
Can be fixed by going into the module's folder, /styles/ and editing the .css file, setting the z-index back to 101 from 9999 ... I'm not sure why this was patched in 1.0.1 version but after reverting it works fine for me.

**Comment by iotech-fvtt** [comment]
@LorduFreeman with your fix (above) the filepicker DOES work, but the module conflicts with the drop-down menus on the MCE - Like Paragraph and font color/background color (if module TinyMCE Toolbar Config is enabled).
@cswendrowski 

Edit: a z-index of 105 (same as z-index of the system filepicker) works (for me at least)
Edit 2: Well, hmm.. the 105 worked up until you actually use the filepicker, afterward it kills the dropdowns again. 
Edit 3: Temporarily solved by adding the following to CustomCSS:
.filepicker {
	z-index: 9999 !important;
}
Not sure why a psuedo-modal system dialog would have such a low z anyway (105)...

**Comment by cswendrowski** [comment]
Please see commentary in https://github.com/cswendrowski/FoundryVTT-TinyMCE-CustomFilePicker/issues/4
