### ISSUE TITLE
Update to v0.8.x

### ISSUE THREAD

**Issue by CapivaraTupiniquim** [cswendrowski/FoundryVTT-TinyMCE-CustomFilePicker#6]
Helo! I really like this module and would like to know if it will be updated.

**Comment by cswendrowski** [comment]
Hey there @GabrielOsvair - glad to hear you like the module!

This has been consumed into core as of 0.8.x, so no need for this module to update: gitlab.com/foundrynet/foundryvtt/-/issues/358
