### ISSUE TITLE
Breaks links on CTRL+Z

### ISSUE THREAD

**Issue by adacosta92** [cswendrowski/FoundryVTT-TinyMCE-CustomFilePicker#7]
Drag an actor/item onto a journal entry to create a link and save it. Then, edit the entry and add a space or something. then tap CTRL+Z a few times and the link will turn from a foundry link into a HTML link. Pressing CTRL+Y fixes this, but it can ruin a lot of hard work.

**Comment by cswendrowski** [comment]
This module is deprecated as it has been consumed into Core, and should not be used in 0.8.X
